api_keys:
  news_api: "your_newsapi_key_here"
  anthropic: "your_anthropic_api_key_here"
  telegram_bot: "your_telegram_bot_token_here"
  reddit_client_id: "your_reddit_client_id"
  reddit_secret: "your_reddit_secret"

telegram:
  chat_ids:
    personal: "your_personal_chat_id"
    alerts: "your_alerts_chat_id"