topics:
  AI:
    keywords: ["artificial intelligence", "machine learning", "deep learning", "LLM", "ChatGPT", "Claude", "GPT"]
    exclude_keywords: ["crypto", "blockchain", "trading"]
    sources: ["newsapi", "reddit", "rss"]
    priority: "high"
    limit: 15
  
  Crypto:
    keywords: ["bitcoin", "ethereum", "cryptocurrency", "blockchain", "defi", "web3"]
    exclude_keywords: ["scam", "rug pull", "meme"]
    sources: ["newsapi", "reddit"]
    priority: "medium"
    limit: 10
  
  Tech:
    keywords: ["technology", "startup", "innovation", "software", "programming"]
    exclude_keywords: ["politics", "sports"]
    sources: ["newsapi", "rss"]
    priority: "medium"
    limit: 8